spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db.cp06k8cc266u.ap-northeast-2.rds.amazonaws.com:3306/library_db
    username: aws
    password: 1q2w3e4!!

